# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
