# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='array_rate_project_indexs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='array_rated_project_indexs',
            field=models.TextField(default='['),
            preserve_default=False,
        ),
    ]
