# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171013_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='array_rate_project_indexs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='array_rated_project_indexs',
            field=models.TextField(blank=True),
        ),
    ]
