# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='home',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
