# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterField(
            model_name='project',
            name='tag_set',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
