# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20171009_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_agent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, validators=[home.models.min_length_3_validator], verbose_name='제목'),
        ),
    ]
