# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20171011_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_agent',
        ),
    ]
