# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, upload_to='home/project/%Y/%m/%d'),
        ),
    ]
