# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20171011_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='value',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
