# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_project_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='value',
            new_name='like',
        ),
    ]
