# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20171014_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.IntegerField(),
        ),
    ]
