# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20171014_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.IntegerField(blank=True),
        ),
    ]
