# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20171014_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='body',
        ),
    ]
