# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
