# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20171106_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=1),
        ),
    ]
