# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20171120_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(default='.', verbose_name='내용'),
        ),
    ]
